[build]
builder = "nixpacks"

[deploy]
startCommand = "./gradlew :server:run --no-daemon"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
JAVA_OPTS = "-Xmx256m -Xms128m -XX:+UseG1GC"
