[build]
builder = "nixpacks"

[deploy]
startCommand = "./gradlew :server:buildFatJar && java -Xmx256m -Xms128m -jar server/build/libs/server-all.jar"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
