[build]
builder = "nixpacks"

[deploy]
startCommand = "chmod +x railway-start.sh && ./railway-start.sh"
healthcheckPath = "/health"

[environments.production.variables]
PORT = "8080"
JAVA_OPTS = "-Xmx512m"
