name: Deploy Backend to Railway

on:
  push:
    branches: [ main ]
    paths: 
      - 'server/**'
      - 'shared/**'
      - 'gradle/**'
      - '*.gradle.kts'
      - 'railway.toml'
      - 'nixpacks.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      - name: Test Server Build
        run: ./gradlew :server:build --no-daemon -x test
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      
      - name: Deploy to Railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
